# Generated by Django 2.1.7 on 2019-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.TextField()),
                ('jobTitle', models.TextField()),
                ('jobLocation', models.TextField()),
                ('employmentType', models.TextField()),
                ('seniorityLevel', models.TextField()),
                ('jobDescription', models.TextField()),
            ],
        ),
    ]
