# Generated by Django 2.1.7 on 2019-03-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField()),
                ('companyName', models.TextField()),
                ('jobTitle', models.TextField()),
                ('jobLocation', models.TextField()),
                ('employmentType', models.TextField()),
                ('seniorityLevel', models.TextField()),
                ('jobDescription', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostJob'),
        ),
    ]
