# Generated by Django 2.1.7 on 2019-03-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.TextField()),
                ('companyNote', models.TextField()),
                ('post_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PostJob')),
            ],
        ),
    ]
